#!groovy

String prmNameTerrafromAction = "terraformaction"
String prmNameAWSResource = "awsresource"

def PROPERTIES_PARAM = [ 
    choice( choices : ['apply', 'destroy'],
        description: "The terraform action that need to performed on the resources",
        name: prmNameTerrafromAction),

    choice( choices: ['vpc', 'ec2-web', 'ec2-app', 'alb-web', 'alb-app', 'rds'],
        description: "AWS Resource that need to be provisioned",
        name: prmNameAWSResource)
]

def PRM_TERRAFORM_ACTION = params[prmNameTerrafromAction]
def PRM_AWS_RESOURCE = params[prmNameAWSResource]

properties([
    parameters(PROPERTIES_PARAM)
])

pipeline {
    agent any

    stages {
        stage ('Running terraform init') {
            steps {
                script {
                    echo "Setting up the workspace"
                    sh """
                        export AWS_DEFAULT_REGION=us-west-2
                        echo "workspace is ${workspace}"
                        cd ${workspace}
                        mkdir provision
                        cp -Rf Challenge-1/Terraform/Resources/$PRM_AWS_RESOURCE/* provision/
                        ls -l
                        ls -l provision/
                    """
                    echo "Checking the terraform version"
                    sh """
                        cd provision/
                        terraform --version
                    """
                    echo "Running the terraform init command"
                    sh """
                        cd provision/
                        terraform init
                    """
                }
            }
        }

        stage ('Running terraform plan') {
            steps {
                script {
                    echo "Running the terraform plan command"
                    sh """
                        export AWS_DEFAULT_REGION=us-west-2
                        cd provision/
                        terraform plan -input=false
                    """
                }
            }
        }

        // stage ('Running Terraform apply or destroy') {
        //     steps {
        //         script {
        //             echo "Running the terraform $PRM_TERRAFORM_ACTION command"
        //             sh """
        //                 export AWS_DEFAULT_REGION=us-west-2
        //                 cd provision/
        //                 terraform $PRM_TERRAFORM_ACTION -input=false --auto-approve
        //             """
        //         }
        //     }
        // }
    }

    post {
        always {
            echo 'cleaning the workspace'
            cleanWs()
        }
    }
}